language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - osx
script:
  - brew install ninja
  - travis_wait cargo build --verbose --all
  - cargo test --verbose --all