language: rust
before_install:
  - bash ./scripts/ninja_install.sh
addons:
  apt:
    packages:
      - python
      - unzip
  bomebrew:
    packages:
      - python
      - llvm
      - unzip
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - osx
  - linux
script:
  - cargo build --verbose --all
  - cargo test --verbose --all