[package]
name = "easy-skia"
version = "0.1.0"
authors = ["Adoo <Adoo@outlook.com>"]
build = "build.rs"

[dependencies]

[dev-dependencies] 
glutin = "0.19.0"
gl = "0.11.0"

[build-dependencies]
bindgen = "0.47.1"